// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadMetrics returns the embedded CollectionSpec for metrics.
func loadMetrics() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MetricsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load metrics: %w", err)
	}

	return spec, err
}

// loadMetricsObjects loads metrics and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*metricsObjects
//	*metricsPrograms
//	*metricsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMetricsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMetrics()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// metricsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metricsSpecs struct {
	metricsProgramSpecs
	metricsMapSpecs
	metricsVariableSpecs
}

// metricsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metricsProgramSpecs struct {
	KprobeInetCskAccept     *ebpf.ProgramSpec `ebpf:"kprobe_inet_csk_accept"`
	KprobeTcpV4Connect      *ebpf.ProgramSpec `ebpf:"kprobe_tcp_v4_connect"`
	TracepointSysEnterWrite *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_write"`
}

// metricsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metricsMapSpecs struct {
	HttpMetrics *ebpf.MapSpec `ebpf:"http_metrics"`
	TcpMetrics  *ebpf.MapSpec `ebpf:"tcp_metrics"`
}

// metricsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type metricsVariableSpecs struct {
}

// metricsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMetricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type metricsObjects struct {
	metricsPrograms
	metricsMaps
	metricsVariables
}

func (o *metricsObjects) Close() error {
	return _MetricsClose(
		&o.metricsPrograms,
		&o.metricsMaps,
	)
}

// metricsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMetricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type metricsMaps struct {
	HttpMetrics *ebpf.Map `ebpf:"http_metrics"`
	TcpMetrics  *ebpf.Map `ebpf:"tcp_metrics"`
}

func (m *metricsMaps) Close() error {
	return _MetricsClose(
		m.HttpMetrics,
		m.TcpMetrics,
	)
}

// metricsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMetricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type metricsVariables struct {
}

// metricsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMetricsObjects or ebpf.CollectionSpec.LoadAndAssign.
type metricsPrograms struct {
	KprobeInetCskAccept     *ebpf.Program `ebpf:"kprobe_inet_csk_accept"`
	KprobeTcpV4Connect      *ebpf.Program `ebpf:"kprobe_tcp_v4_connect"`
	TracepointSysEnterWrite *ebpf.Program `ebpf:"tracepoint_sys_enter_write"`
}

func (p *metricsPrograms) Close() error {
	return _MetricsClose(
		p.KprobeInetCskAccept,
		p.KprobeTcpV4Connect,
		p.TracepointSysEnterWrite,
	)
}

func _MetricsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed metrics_bpfel.o
var _MetricsBytes []byte
