// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/query.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Table int32

const (
	Table_TABLE_UNSPECIFIED Table = 0
	Table_LOGS              Table = 1
	Table_TRACES            Table = 2
	Table_METRICS           Table = 3
)

// Enum value maps for Table.
var (
	Table_name = map[int32]string{
		0: "TABLE_UNSPECIFIED",
		1: "LOGS",
		2: "TRACES",
		3: "METRICS",
	}
	Table_value = map[string]int32{
		"TABLE_UNSPECIFIED": 0,
		"LOGS":              1,
		"TRACES":            2,
		"METRICS":           3,
	}
)

func (x Table) Enum() *Table {
	p := new(Table)
	*p = x
	return p
}

func (x Table) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Table) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_query_proto_enumTypes[0].Descriptor()
}

func (Table) Type() protoreflect.EnumType {
	return &file_proto_query_proto_enumTypes[0]
}

func (x Table) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Table.Descriptor instead.
func (Table) EnumDescriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{0}
}

type FrontendQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         Table                  `protobuf:"varint,1,opt,name=table,proto3,enum=opentelemetry.Table" json:"table,omitempty"`
	Filters       []string               `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendQueryRequest) Reset() {
	*x = FrontendQueryRequest{}
	mi := &file_proto_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendQueryRequest) ProtoMessage() {}

func (x *FrontendQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendQueryRequest.ProtoReflect.Descriptor instead.
func (*FrontendQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{0}
}

func (x *FrontendQueryRequest) GetTable() Table {
	if x != nil {
		return x.Table
	}
	return Table_TABLE_UNSPECIFIED
}

func (x *FrontendQueryRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type FrontendQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       [][]byte               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendQueryResponse) Reset() {
	*x = FrontendQueryResponse{}
	mi := &file_proto_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendQueryResponse) ProtoMessage() {}

func (x *FrontendQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendQueryResponse.ProtoReflect.Descriptor instead.
func (*FrontendQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_query_proto_rawDescGZIP(), []int{1}
}

func (x *FrontendQueryResponse) GetResults() [][]byte {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_query_proto protoreflect.FileDescriptor

const file_proto_query_proto_rawDesc = "" +
	"\n" +
	"\x11proto/query.proto\x12\ropentelemetry\"\\\n" +
	"\x14FrontendQueryRequest\x12*\n" +
	"\x05table\x18\x01 \x01(\x0e2\x14.opentelemetry.TableR\x05table\x12\x18\n" +
	"\afilters\x18\x02 \x03(\tR\afilters\"1\n" +
	"\x15FrontendQueryResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\fR\aresults*A\n" +
	"\x05Table\x12\x15\n" +
	"\x11TABLE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04LOGS\x10\x01\x12\n" +
	"\n" +
	"\x06TRACES\x10\x02\x12\v\n" +
	"\aMETRICS\x10\x032l\n" +
	"\x14FrontendQueryService\x12T\n" +
	"\x05Query\x12#.opentelemetry.FrontendQueryRequest\x1a$.opentelemetry.FrontendQueryResponse0\x01BCZAgithub.com/gke-labs/in-cluster-observability/opentelemetry/pkg/pbb\x06proto3"

var (
	file_proto_query_proto_rawDescOnce sync.Once
	file_proto_query_proto_rawDescData []byte
)

func file_proto_query_proto_rawDescGZIP() []byte {
	file_proto_query_proto_rawDescOnce.Do(func() {
		file_proto_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_query_proto_rawDesc), len(file_proto_query_proto_rawDesc)))
	})
	return file_proto_query_proto_rawDescData
}

var file_proto_query_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_query_proto_goTypes = []any{
	(Table)(0),                    // 0: opentelemetry.Table
	(*FrontendQueryRequest)(nil),  // 1: opentelemetry.FrontendQueryRequest
	(*FrontendQueryResponse)(nil), // 2: opentelemetry.FrontendQueryResponse
}
var file_proto_query_proto_depIdxs = []int32{
	0, // 0: opentelemetry.FrontendQueryRequest.table:type_name -> opentelemetry.Table
	1, // 1: opentelemetry.FrontendQueryService.Query:input_type -> opentelemetry.FrontendQueryRequest
	2, // 2: opentelemetry.FrontendQueryService.Query:output_type -> opentelemetry.FrontendQueryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_query_proto_init() }
func file_proto_query_proto_init() {
	if File_proto_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_query_proto_rawDesc), len(file_proto_query_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_query_proto_goTypes,
		DependencyIndexes: file_proto_query_proto_depIdxs,
		EnumInfos:         file_proto_query_proto_enumTypes,
		MessageInfos:      file_proto_query_proto_msgTypes,
	}.Build()
	File_proto_query_proto = out.File
	file_proto_query_proto_goTypes = nil
	file_proto_query_proto_depIdxs = nil
}
