// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: query.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FrontendQueryService_Query_FullMethodName = "/opentelemetry.FrontendQueryService/Query"
)

// FrontendQueryServiceClient is the client API for FrontendQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontendQueryServiceClient interface {
	Query(ctx context.Context, in *FrontendQueryRequest, opts ...grpc.CallOption) (*FrontendQueryResponse, error)
}

type frontendQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontendQueryServiceClient(cc grpc.ClientConnInterface) FrontendQueryServiceClient {
	return &frontendQueryServiceClient{cc}
}

func (c *frontendQueryServiceClient) Query(ctx context.Context, in *FrontendQueryRequest, opts ...grpc.CallOption) (*FrontendQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrontendQueryResponse)
	err := c.cc.Invoke(ctx, FrontendQueryService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrontendQueryServiceServer is the server API for FrontendQueryService service.
// All implementations must embed UnimplementedFrontendQueryServiceServer
// for forward compatibility.
type FrontendQueryServiceServer interface {
	Query(context.Context, *FrontendQueryRequest) (*FrontendQueryResponse, error)
	mustEmbedUnimplementedFrontendQueryServiceServer()
}

// UnimplementedFrontendQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFrontendQueryServiceServer struct{}

func (UnimplementedFrontendQueryServiceServer) Query(context.Context, *FrontendQueryRequest) (*FrontendQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedFrontendQueryServiceServer) mustEmbedUnimplementedFrontendQueryServiceServer() {}
func (UnimplementedFrontendQueryServiceServer) testEmbeddedByValue()                              {}

// UnsafeFrontendQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontendQueryServiceServer will
// result in compilation errors.
type UnsafeFrontendQueryServiceServer interface {
	mustEmbedUnimplementedFrontendQueryServiceServer()
}

func RegisterFrontendQueryServiceServer(s grpc.ServiceRegistrar, srv FrontendQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedFrontendQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FrontendQueryService_ServiceDesc, srv)
}

func _FrontendQueryService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrontendQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrontendQueryServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FrontendQueryService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrontendQueryServiceServer).Query(ctx, req.(*FrontendQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FrontendQueryService_ServiceDesc is the grpc.ServiceDesc for FrontendQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrontendQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opentelemetry.FrontendQueryService",
	HandlerType: (*FrontendQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _FrontendQueryService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query.proto",
}
