// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Address of the sink (host:port).
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Elements are OTLP messages (e.g., ExportMetricsServiceRequest) marshaled to binary proto.
	Metrics       [][]byte `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Logs          [][]byte `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
	Traces        [][]byte `protobuf:"bytes,3,rep,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetMetrics() [][]byte {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *QueryResponse) GetLogs() [][]byte {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *QueryResponse) GetTraces() [][]byte {
	if x != nil {
		return x.Traces
	}
	return nil
}

type SearchLogsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartTimeUnixNano int64                  `protobuf:"varint,1,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	EndTimeUnixNano   int64                  `protobuf:"varint,2,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	BodyContains      []string               `protobuf:"bytes,3,rep,name=body_contains,json=bodyContains,proto3" json:"body_contains,omitempty"` // case-insensitive substrings, ANDed
	Attributes        []*AttributeFilter     `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`                         // ANDed
	Limit             int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                  // per-sink cap
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchLogsRequest) Reset() {
	*x = SearchLogsRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsRequest) ProtoMessage() {}

func (x *SearchLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchLogsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchLogsRequest) GetStartTimeUnixNano() int64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *SearchLogsRequest) GetEndTimeUnixNano() int64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

func (x *SearchLogsRequest) GetBodyContains() []string {
	if x != nil {
		return x.BodyContains
	}
	return nil
}

func (x *SearchLogsRequest) GetAttributes() []*AttributeFilter {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *SearchLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AttributeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // resolved key, e.g. "k8s.namespace.name"; "SeverityText" handled as a well-known field
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // supports '*' glob
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeFilter) Reset() {
	*x = AttributeFilter{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeFilter) ProtoMessage() {}

func (x *AttributeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeFilter.ProtoReflect.Descriptor instead.
func (*AttributeFilter) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *AttributeFilter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AttributeFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SearchLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          [][]byte               `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsResponse) Reset() {
	*x = SearchLogsResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsResponse) ProtoMessage() {}

func (x *SearchLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsResponse.ProtoReflect.Descriptor instead.
func (*SearchLogsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *SearchLogsResponse) GetLogs() [][]byte {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\ropentelemetry\"+\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x12\n" +
	"\x10RegisterResponse\"$\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"U\n" +
	"\rQueryResponse\x12\x18\n" +
	"\ametrics\x18\x01 \x03(\fR\ametrics\x12\x12\n" +
	"\x04logs\x18\x02 \x03(\fR\x04logs\x12\x16\n" +
	"\x06traces\x18\x03 \x03(\fR\x06traces\"\xec\x01\n" +
	"\x11SearchLogsRequest\x12/\n" +
	"\x14start_time_unix_nano\x18\x01 \x01(\x03R\x11startTimeUnixNano\x12+\n" +
	"\x12end_time_unix_nano\x18\x02 \x01(\x03R\x0fendTimeUnixNano\x12#\n" +
	"\rbody_contains\x18\x03 \x03(\tR\fbodyContains\x12>\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x1e.opentelemetry.AttributeFilterR\n" +
	"attributes\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"9\n" +
	"\x0fAttributeFilter\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"(\n" +
	"\x12SearchLogsResponse\x12\x12\n" +
	"\x04logs\x18\x01 \x03(\fR\x04logs2f\n" +
	"\x13RegistrationService\x12O\n" +
	"\bRegister\x12\x1e.opentelemetry.RegisterRequest\x1a\x1f.opentelemetry.RegisterResponse(\x010\x012\xa9\x01\n" +
	"\fQueryService\x12D\n" +
	"\x05Query\x12\x1b.opentelemetry.QueryRequest\x1a\x1c.opentelemetry.QueryResponse0\x01\x12S\n" +
	"\n" +
	"SearchLogs\x12 .opentelemetry.SearchLogsRequest\x1a!.opentelemetry.SearchLogsResponse0\x01BCZAgithub.com/gke-labs/in-cluster-observability/opentelemetry/pkg/pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_proto_goTypes = []any{
	(*RegisterRequest)(nil),    // 0: opentelemetry.RegisterRequest
	(*RegisterResponse)(nil),   // 1: opentelemetry.RegisterResponse
	(*QueryRequest)(nil),       // 2: opentelemetry.QueryRequest
	(*QueryResponse)(nil),      // 3: opentelemetry.QueryResponse
	(*SearchLogsRequest)(nil),  // 4: opentelemetry.SearchLogsRequest
	(*AttributeFilter)(nil),    // 5: opentelemetry.AttributeFilter
	(*SearchLogsResponse)(nil), // 6: opentelemetry.SearchLogsResponse
}
var file_service_proto_depIdxs = []int32{
	5, // 0: opentelemetry.SearchLogsRequest.attributes:type_name -> opentelemetry.AttributeFilter
	0, // 1: opentelemetry.RegistrationService.Register:input_type -> opentelemetry.RegisterRequest
	2, // 2: opentelemetry.QueryService.Query:input_type -> opentelemetry.QueryRequest
	4, // 3: opentelemetry.QueryService.SearchLogs:input_type -> opentelemetry.SearchLogsRequest
	1, // 4: opentelemetry.RegistrationService.Register:output_type -> opentelemetry.RegisterResponse
	3, // 5: opentelemetry.QueryService.Query:output_type -> opentelemetry.QueryResponse
	6, // 6: opentelemetry.QueryService.SearchLogs:output_type -> opentelemetry.SearchLogsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
