//go:build !ignore_autogenerated

// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicy) DeepCopyInto(out *ClusterTrafficPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicy.
func (in *ClusterTrafficPolicy) DeepCopy() *ClusterTrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTrafficPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicyList) DeepCopyInto(out *ClusterTrafficPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterTrafficPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicyList.
func (in *ClusterTrafficPolicyList) DeepCopy() *ClusterTrafficPolicyList {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterTrafficPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicySpec) DeepCopyInto(out *ClusterTrafficPolicySpec) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.WorkloadSelector != nil {
		in, out := &in.WorkloadSelector, &out.WorkloadSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	in.MonitoringSpecCore.DeepCopyInto(&out.MonitoringSpecCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicySpec.
func (in *ClusterTrafficPolicySpec) DeepCopy() *ClusterTrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterTrafficPolicyStatus) DeepCopyInto(out *ClusterTrafficPolicyStatus) {
	*out = *in
	in.MonitoringStatusCore.DeepCopyInto(&out.MonitoringStatusCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterTrafficPolicyStatus.
func (in *ClusterTrafficPolicyStatus) DeepCopy() *ClusterTrafficPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterTrafficPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GRPCConfig) DeepCopyInto(out *GRPCConfig) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GRPCConfig.
func (in *GRPCConfig) DeepCopy() *GRPCConfig {
	if in == nil {
		return nil
	}
	out := new(GRPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPConfig) DeepCopyInto(out *HTTPConfig) {
	*out = *in
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPConfig.
func (in *HTTPConfig) DeepCopy() *HTTPConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L4Config) DeepCopyInto(out *L4Config) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L4Config.
func (in *L4Config) DeepCopy() *L4Config {
	if in == nil {
		return nil
	}
	out := new(L4Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpecCore) DeepCopyInto(out *MonitoringSpecCore) {
	*out = *in
	in.Protocols.DeepCopyInto(&out.Protocols)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpecCore.
func (in *MonitoringSpecCore) DeepCopy() *MonitoringSpecCore {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpecCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringStatusCore) DeepCopyInto(out *MonitoringStatusCore) {
	*out = *in
	if in.MatchedPodSample != nil {
		in, out := &in.MatchedPodSample, &out.MatchedPodSample
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conflicts != nil {
		in, out := &in.Conflicts, &out.Conflicts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringStatusCore.
func (in *MonitoringStatusCore) DeepCopy() *MonitoringStatusCore {
	if in == nil {
		return nil
	}
	out := new(MonitoringStatusCore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProtocolSet) DeepCopyInto(out *ProtocolSet) {
	*out = *in
	if in.L4 != nil {
		in, out := &in.L4, &out.L4
		*out = new(L4Config)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GRPC != nil {
		in, out := &in.GRPC, &out.GRPC
		*out = new(GRPCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProtocolSet.
func (in *ProtocolSet) DeepCopy() *ProtocolSet {
	if in == nil {
		return nil
	}
	out := new(ProtocolSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficMonitor) DeepCopyInto(out *TrafficMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficMonitor.
func (in *TrafficMonitor) DeepCopy() *TrafficMonitor {
	if in == nil {
		return nil
	}
	out := new(TrafficMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficMonitorList) DeepCopyInto(out *TrafficMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficMonitorList.
func (in *TrafficMonitorList) DeepCopy() *TrafficMonitorList {
	if in == nil {
		return nil
	}
	out := new(TrafficMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficMonitorSpec) DeepCopyInto(out *TrafficMonitorSpec) {
	*out = *in
	in.WorkloadSelector.DeepCopyInto(&out.WorkloadSelector)
	in.MonitoringSpecCore.DeepCopyInto(&out.MonitoringSpecCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficMonitorSpec.
func (in *TrafficMonitorSpec) DeepCopy() *TrafficMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficMonitorStatus) DeepCopyInto(out *TrafficMonitorStatus) {
	*out = *in
	in.MonitoringStatusCore.DeepCopyInto(&out.MonitoringStatusCore)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficMonitorStatus.
func (in *TrafficMonitorStatus) DeepCopy() *TrafficMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficMonitorStatus)
	in.DeepCopyInto(out)
	return out
}
