// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: stream/v1/stream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamService_SubscribeSpans_FullMethodName = "/ollie.stream.v1.StreamService/SubscribeSpans"
	StreamService_StreamMetrics_FullMethodName  = "/ollie.stream.v1.StreamService/StreamMetrics"
)

// StreamServiceClient is the client API for StreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StreamService is the live subscription surface (#99, ADR-0026 §7):
// CEL-filtered spans and periodic PromQL evaluations as server
// streams. Served by the query server (cluster-wide, multiplexed
// across agents) and by each agent (node-local; the query server's
// upstream). Span payloads are serialized OTLP so any OpenTelemetry
// tooling consumes them directly.
type StreamServiceClient interface {
	// SubscribeSpans streams spans matching the CEL filter as they are
	// captured. Slow consumers lose the oldest undelivered spans; the
	// loss surfaces as SpanEvent.gap on the next delivery, never as
	// backpressure into capture.
	SubscribeSpans(ctx context.Context, in *SubscribeSpansRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpanEvent], error)
	// StreamMetrics evaluates a PromQL instant query every step and
	// streams the resulting samples.
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricSample], error)
}

type streamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamServiceClient(cc grpc.ClientConnInterface) StreamServiceClient {
	return &streamServiceClient{cc}
}

func (c *streamServiceClient) SubscribeSpans(ctx context.Context, in *SubscribeSpansRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SpanEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[0], StreamService_SubscribeSpans_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeSpansRequest, SpanEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_SubscribeSpansClient = grpc.ServerStreamingClient[SpanEvent]

func (c *streamServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MetricSample], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamService_ServiceDesc.Streams[1], StreamService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, MetricSample]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamMetricsClient = grpc.ServerStreamingClient[MetricSample]

// StreamServiceServer is the server API for StreamService service.
// All implementations must embed UnimplementedStreamServiceServer
// for forward compatibility.
//
// StreamService is the live subscription surface (#99, ADR-0026 §7):
// CEL-filtered spans and periodic PromQL evaluations as server
// streams. Served by the query server (cluster-wide, multiplexed
// across agents) and by each agent (node-local; the query server's
// upstream). Span payloads are serialized OTLP so any OpenTelemetry
// tooling consumes them directly.
type StreamServiceServer interface {
	// SubscribeSpans streams spans matching the CEL filter as they are
	// captured. Slow consumers lose the oldest undelivered spans; the
	// loss surfaces as SpanEvent.gap on the next delivery, never as
	// backpressure into capture.
	SubscribeSpans(*SubscribeSpansRequest, grpc.ServerStreamingServer[SpanEvent]) error
	// StreamMetrics evaluates a PromQL instant query every step and
	// streams the resulting samples.
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricSample]) error
	mustEmbedUnimplementedStreamServiceServer()
}

// UnimplementedStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamServiceServer struct{}

func (UnimplementedStreamServiceServer) SubscribeSpans(*SubscribeSpansRequest, grpc.ServerStreamingServer[SpanEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeSpans not implemented")
}
func (UnimplementedStreamServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[MetricSample]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedStreamServiceServer) mustEmbedUnimplementedStreamServiceServer() {}
func (UnimplementedStreamServiceServer) testEmbeddedByValue()                       {}

// UnsafeStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServiceServer will
// result in compilation errors.
type UnsafeStreamServiceServer interface {
	mustEmbedUnimplementedStreamServiceServer()
}

func RegisterStreamServiceServer(s grpc.ServiceRegistrar, srv StreamServiceServer) {
	// If the following call panics, it indicates UnimplementedStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamService_ServiceDesc, srv)
}

func _StreamService_SubscribeSpans_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeSpansRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).SubscribeSpans(m, &grpc.GenericServerStream[SubscribeSpansRequest, SpanEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_SubscribeSpansServer = grpc.ServerStreamingServer[SpanEvent]

func _StreamService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServiceServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, MetricSample]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamService_StreamMetricsServer = grpc.ServerStreamingServer[MetricSample]

// StreamService_ServiceDesc is the grpc.ServiceDesc for StreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ollie.stream.v1.StreamService",
	HandlerType: (*StreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeSpans",
			Handler:       _StreamService_SubscribeSpans_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamMetrics",
			Handler:       _StreamService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stream/v1/stream.proto",
}
