// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: stream/v1/stream.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeSpansRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cel_filter is a CEL expression over the variables `span`
	// (opentelemetry.proto.trace.v1.Span) and `resource`
	// (map<string,string> of resource attributes). Empty matches
	// everything. Example:
	//
	//	resource["k8s.namespace.name"] == "shop" &&
	//	span.kind == 2 // SPAN_KIND_SERVER
	CelFilter     string `protobuf:"bytes,1,opt,name=cel_filter,json=celFilter,proto3" json:"cel_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeSpansRequest) Reset() {
	*x = SubscribeSpansRequest{}
	mi := &file_stream_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeSpansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeSpansRequest) ProtoMessage() {}

func (x *SubscribeSpansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeSpansRequest.ProtoReflect.Descriptor instead.
func (*SubscribeSpansRequest) Descriptor() ([]byte, []int) {
	return file_stream_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeSpansRequest) GetCelFilter() string {
	if x != nil {
		return x.CelFilter
	}
	return ""
}

type SpanEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// span is a serialized opentelemetry.proto.trace.v1.Span.
	Span []byte `protobuf:"bytes,1,opt,name=span,proto3" json:"span,omitempty"`
	// resource holds the span's OTLP resource attributes, flattened
	// to strings.
	Resource map[string]string `protobuf:"bytes,2,rep,name=resource,proto3" json:"resource,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// gap counts spans this subscriber lost (drop-oldest) since the
	// previous delivery.
	Gap           uint64 `protobuf:"varint,3,opt,name=gap,proto3" json:"gap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanEvent) Reset() {
	*x = SpanEvent{}
	mi := &file_stream_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanEvent) ProtoMessage() {}

func (x *SpanEvent) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanEvent.ProtoReflect.Descriptor instead.
func (*SpanEvent) Descriptor() ([]byte, []int) {
	return file_stream_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *SpanEvent) GetSpan() []byte {
	if x != nil {
		return x.Span
	}
	return nil
}

func (x *SpanEvent) GetResource() map[string]string {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *SpanEvent) GetGap() uint64 {
	if x != nil {
		return x.Gap
	}
	return 0
}

type StreamMetricsRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Promql string                 `protobuf:"bytes,1,opt,name=promql,proto3" json:"promql,omitempty"`
	// step_ms is the evaluation cadence in milliseconds. Defaults to
	// 15000; the server clamps to [1000, 300000].
	StepMs        int64 `protobuf:"varint,2,opt,name=step_ms,json=stepMs,proto3" json:"step_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_stream_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_stream_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamMetricsRequest) GetPromql() string {
	if x != nil {
		return x.Promql
	}
	return ""
}

func (x *StreamMetricsRequest) GetStepMs() int64 {
	if x != nil {
		return x.StepMs
	}
	return 0
}

type MetricSample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// labels includes __name__ when the result carries one.
	Labels      map[string]string `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Value       float64           `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	TimestampMs int64             `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// degraded is true when the fan-out behind this evaluation missed
	// at least one agent (storage-and-query.md §5.3).
	Degraded      bool `protobuf:"varint,4,opt,name=degraded,proto3" json:"degraded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSample) Reset() {
	*x = MetricSample{}
	mi := &file_stream_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSample) ProtoMessage() {}

func (x *MetricSample) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSample.ProtoReflect.Descriptor instead.
func (*MetricSample) Descriptor() ([]byte, []int) {
	return file_stream_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *MetricSample) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricSample) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *MetricSample) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

var File_stream_v1_stream_proto protoreflect.FileDescriptor

const file_stream_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x16stream/v1/stream.proto\x12\x0follie.stream.v1\"6\n" +
	"\x15SubscribeSpansRequest\x12\x1d\n" +
	"\n" +
	"cel_filter\x18\x01 \x01(\tR\tcelFilter\"\xb4\x01\n" +
	"\tSpanEvent\x12\x12\n" +
	"\x04span\x18\x01 \x01(\fR\x04span\x12D\n" +
	"\bresource\x18\x02 \x03(\v2(.ollie.stream.v1.SpanEvent.ResourceEntryR\bresource\x12\x10\n" +
	"\x03gap\x18\x03 \x01(\x04R\x03gap\x1a;\n" +
	"\rResourceEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x14StreamMetricsRequest\x12\x16\n" +
	"\x06promql\x18\x01 \x01(\tR\x06promql\x12\x17\n" +
	"\astep_ms\x18\x02 \x01(\x03R\x06stepMs\"\xe1\x01\n" +
	"\fMetricSample\x12A\n" +
	"\x06labels\x18\x01 \x03(\v2).ollie.stream.v1.MetricSample.LabelsEntryR\x06labels\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x1a\n" +
	"\bdegraded\x18\x04 \x01(\bR\bdegraded\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc0\x01\n" +
	"\rStreamService\x12V\n" +
	"\x0eSubscribeSpans\x12&.ollie.stream.v1.SubscribeSpansRequest\x1a\x1a.ollie.stream.v1.SpanEvent0\x01\x12W\n" +
	"\rStreamMetrics\x12%.ollie.stream.v1.StreamMetricsRequest\x1a\x1d.ollie.stream.v1.MetricSample0\x01B<Z:github.com/gke-labs/in-cluster-observability/pkg/stream/pbb\x06proto3"

var (
	file_stream_v1_stream_proto_rawDescOnce sync.Once
	file_stream_v1_stream_proto_rawDescData []byte
)

func file_stream_v1_stream_proto_rawDescGZIP() []byte {
	file_stream_v1_stream_proto_rawDescOnce.Do(func() {
		file_stream_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_v1_stream_proto_rawDesc), len(file_stream_v1_stream_proto_rawDesc)))
	})
	return file_stream_v1_stream_proto_rawDescData
}

var file_stream_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_stream_v1_stream_proto_goTypes = []any{
	(*SubscribeSpansRequest)(nil), // 0: ollie.stream.v1.SubscribeSpansRequest
	(*SpanEvent)(nil),             // 1: ollie.stream.v1.SpanEvent
	(*StreamMetricsRequest)(nil),  // 2: ollie.stream.v1.StreamMetricsRequest
	(*MetricSample)(nil),          // 3: ollie.stream.v1.MetricSample
	nil,                           // 4: ollie.stream.v1.SpanEvent.ResourceEntry
	nil,                           // 5: ollie.stream.v1.MetricSample.LabelsEntry
}
var file_stream_v1_stream_proto_depIdxs = []int32{
	4, // 0: ollie.stream.v1.SpanEvent.resource:type_name -> ollie.stream.v1.SpanEvent.ResourceEntry
	5, // 1: ollie.stream.v1.MetricSample.labels:type_name -> ollie.stream.v1.MetricSample.LabelsEntry
	0, // 2: ollie.stream.v1.StreamService.SubscribeSpans:input_type -> ollie.stream.v1.SubscribeSpansRequest
	2, // 3: ollie.stream.v1.StreamService.StreamMetrics:input_type -> ollie.stream.v1.StreamMetricsRequest
	1, // 4: ollie.stream.v1.StreamService.SubscribeSpans:output_type -> ollie.stream.v1.SpanEvent
	3, // 5: ollie.stream.v1.StreamService.StreamMetrics:output_type -> ollie.stream.v1.MetricSample
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stream_v1_stream_proto_init() }
func file_stream_v1_stream_proto_init() {
	if File_stream_v1_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_v1_stream_proto_rawDesc), len(file_stream_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_v1_stream_proto_goTypes,
		DependencyIndexes: file_stream_v1_stream_proto_depIdxs,
		MessageInfos:      file_stream_v1_stream_proto_msgTypes,
	}.Build()
	File_stream_v1_stream_proto = out.File
	file_stream_v1_stream_proto_goTypes = nil
	file_stream_v1_stream_proto_depIdxs = nil
}
