// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package obi is the OBI adapter contract-test harness. It feeds
// pinned OTLP payloads (binary protobuf, captured from real OBI runs)
// through our agent's OTLP receiver + translator, captures the
// resulting capture.Event stream, and diffs it against committed
// golden JSON. Per docs/design/obi-integration.md §6, this freezes
// our OTLP→Event translation so OBI image bumps cannot silently
// change us.
//
// Fixture format on disk:
//
//	testdata/<category>/<case>/input.binpb  (serialized OTLP request)
//	testdata/<category>/<case>/kind          ("metrics" | "traces")
//	testdata/<category>/<case>/golden.json   (expected []Event)
//
// Goldens are regenerated by running `go test -update`. See
// REGENERATE.md in this directory for how to regenerate the input
// fixtures from a real OBI sidecar.
package obi

import (
	"encoding/json"
	"errors"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	collmetricspb "go.opentelemetry.io/proto/otlp/collector/metrics/v1"
	colltracepb "go.opentelemetry.io/proto/otlp/collector/trace/v1"
	"google.golang.org/protobuf/proto"

	"github.com/gke-labs/in-cluster-observability/pkg/capture"
)

// updateGoldens is set by `go test -update`; when true the harness
// rewrites golden.json from the actual translator output instead of
// diffing against it.
var updateGoldens = flag.Bool("update", false, "regenerate golden.json files from current translator output")

// Goldens are compared structurally — field ordering inside maps and
// slice element ordering must match the translator's deterministic
// output. Timestamps are normalized to zero so goldens stay stable
// across runs.
type goldenEvent struct {
	Kind       string            `json:"kind"`
	Module     string            `json:"module"`
	Metric     *goldenMetric     `json:"metric,omitempty"`
	Span       *goldenSpan       `json:"span,omitempty"`
	Attributes map[string]string `json:"attributes,omitempty"`
}

type goldenMetric struct {
	Name       string            `json:"name"`
	Value      float64           `json:"value"`
	Attributes map[string]string `json:"attributes,omitempty"`

	// Typed re-emission contract (#153): a pinned OBI image that flips
	// a metric's type, temporality, monotonicity, or bucket layout is
	// a breaking change this golden must catch — those fields decide
	// whether :9090 counters inflate.
	Type         string    `json:"type,omitempty"`
	Temporality  string    `json:"temporality,omitempty"`
	Monotonic    bool      `json:"monotonic,omitempty"`
	Count        uint64    `json:"count,omitempty"`
	Bounds       []float64 `json:"bounds,omitempty"`
	BucketCounts []uint64  `json:"bucket_counts,omitempty"`
}

func metricTypeString(t capture.MetricType) string {
	switch t {
	case capture.MetricTypeSum:
		return "sum"
	case capture.MetricTypeGauge:
		return "gauge"
	case capture.MetricTypeHistogram:
		return "histogram"
	default:
		return ""
	}
}

func temporalityString(t capture.Temporality) string {
	switch t {
	case capture.TemporalityDelta:
		return "delta"
	case capture.TemporalityCumulative:
		return "cumulative"
	default:
		return ""
	}
}

type goldenSpan struct {
	Name       string            `json:"name"`
	Method     string            `json:"method,omitempty"`
	Path       string            `json:"path,omitempty"`
	StatusCode int               `json:"status_code,omitempty"`
	DurationNs uint64            `json:"duration_ns,omitempty"`
	Attributes map[string]string `json:"attributes,omitempty"`
}

// loadCase reads a fixture directory: returns the kind ("metrics" /
// "traces"), the parsed OTLP message, and the path to golden.json.
func loadCase(t *testing.T, dir string) (kind string, msg proto.Message, goldenPath string) {
	t.Helper()
	kindB, err := os.ReadFile(filepath.Join(dir, "kind"))
	if err != nil {
		t.Fatalf("read kind: %v", err)
	}
	kind = strings.TrimSpace(string(kindB))
	body, err := os.ReadFile(filepath.Join(dir, "input.binpb"))
	if err != nil {
		t.Fatalf("read input.binpb: %v", err)
	}
	switch kind {
	case "metrics":
		m := &collmetricspb.ExportMetricsServiceRequest{}
		if err := proto.Unmarshal(body, m); err != nil {
			t.Fatalf("unmarshal metrics: %v", err)
		}
		return kind, m, filepath.Join(dir, "golden.json")
	case "traces":
		m := &colltracepb.ExportTraceServiceRequest{}
		if err := proto.Unmarshal(body, m); err != nil {
			t.Fatalf("unmarshal traces: %v", err)
		}
		return kind, m, filepath.Join(dir, "golden.json")
	}
	t.Fatalf("unknown kind %q (expect 'metrics' or 'traces')", kind)
	return "", nil, ""
}

// writeBinpb is a tiny helper for cases that build fixtures
// programmatically (in lieu of recordings from a real OBI). The
// REGENERATE.md doc walks operators through replacing these with
// recorded fixtures.
func writeBinpb(t *testing.T, dir, kind string, msg proto.Message) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	body, err := proto.Marshal(msg)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "input.binpb"), body, 0o644); err != nil {
		t.Fatalf("write input.binpb: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "kind"), []byte(kind+"\n"), 0o644); err != nil {
		t.Fatalf("write kind: %v", err)
	}
}

// compareOrUpdate diffs actual JSON against the golden file. If
// -update is set, rewrites the golden file from actual instead.
func compareOrUpdate(t *testing.T, goldenPath string, actual []goldenEvent) {
	t.Helper()
	actualJSON, err := json.MarshalIndent(actual, "", "  ")
	if err != nil {
		t.Fatalf("marshal actual: %v", err)
	}
	if *updateGoldens {
		if err := os.WriteFile(goldenPath, actualJSON, 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("updated %s", goldenPath)
		return
	}
	want, err := os.ReadFile(goldenPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			t.Fatalf("golden file missing: %s (run `go test -update` to create)", goldenPath)
		}
		t.Fatalf("read golden: %v", err)
	}
	if string(want) != string(actualJSON) {
		t.Errorf("golden mismatch for %s\n--- want ---\n%s\n--- got ---\n%s\n(run `go test -update` to refresh)", goldenPath, string(want), string(actualJSON))
	}
}
